### PR TITLE
Remove unused random-lib dependency and cull package-lock.json.

### PR DESCRIPTION
**Pull request by riastradh-brave**

### CODE REVIEW

**Review by mrose17 — CHANGES_REQUESTED** [review]
Can you bump the version number in package.json?

**Review by mrose17 — CHANGES_REQUESTED** [review]
Can you bump the version number in package.json?

**Comment by riastradh-brave** [comment]
@mrose17 Version bumped in 9d7faad72a1ead111c20ad24b1cbd9a31f6a3940.

**Review by mrose17 — COMMENTED** [review]
LGTM.

**Review by mrose17 — APPROVED** [review]

**Pull request merged**
